[2024-07-08T10:44:38.226+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T10:44:38.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_branch.DAG_5_branch manual__2024-07-08T10:44:15.596541+00:00 [queued]>
[2024-07-08T10:44:38.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_branch.DAG_5_branch manual__2024-07-08T10:44:15.596541+00:00 [queued]>
[2024-07-08T10:44:38.276+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T10:44:38.298+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): DAG_5_branch> on 2024-07-08 10:44:15.596541+00:00
[2024-07-08T10:44:38.330+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2092) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T10:44:38.330+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'master_branch', 'DAG_5_branch', 'manual__2024-07-08T10:44:15.596541+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/master_bracnh.py', '--cfg-path', '/tmp/tmpgg89trut']
[2024-07-08T10:44:38.347+0000] {standard_task_runner.py:63} INFO - Started process 2097 to run task
[2024-07-08T10:44:38.347+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask DAG_5_branch
[2024-07-08T10:44:50.496+0000] {cli_action_loggers.py:137} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-08T10:44:50.791+0000] {task_command.py:426} INFO - Running <TaskInstance: master_branch.DAG_5_branch manual__2024-07-08T10:44:15.596541+00:00 [running]> on host 0ffcb94bda06
[2024-07-08T10:45:08.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='master_branch' AIRFLOW_CTX_TASK_ID='DAG_5_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T10:44:15.596541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T10:44:15.596541+00:00'
[2024-07-08T10:45:08.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T10:45:08.824+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-08T10:45:08.840+0000] {logging_mixin.py:188} INFO - The DAG DAG_5 was triggered 1 times today.
[2024-07-08T10:45:08.841+0000] {python.py:237} INFO - Done. Returned value was: ['already_triggered_DAG_5']
[2024-07-08T10:45:08.842+0000] {branch.py:36} INFO - Branch into ['already_triggered_DAG_5']
[2024-07-08T10:45:08.842+0000] {skipmixin.py:178} INFO - Following branch ['already_triggered_DAG_5']
[2024-07-08T10:45:08.896+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip_DAG_5', -1), ('trigger_DAG_5', -1)]
[2024-07-08T10:45:08.930+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T10:45:08.956+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=master_branch, task_id=DAG_5_branch, run_id=manual__2024-07-08T10:44:15.596541+00:00, execution_date=20240708T104415, start_date=20240708T104438, end_date=20240708T104508
[2024-07-08T10:45:09.010+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-08T10:45:09.045+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T10:45:09.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
